[package]
name = "sol-batch-token-transfer"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.9.13"
solana-sdk = "1.9.13"
spl-token = "3.2.0"
spl-associated-token-account = "1.0.3"
dotenv = "0.15.0"
csv = "1.1"
serde = { version = "1", features = ["derive"] }